name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Composer dumpautoload
        run: composer dumpautoload

      - name: Setup database
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE USER 'ubuntu'@'%' IDENTIFIED BY 'vagrant'"
          mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL ON *.* TO 'ubuntu'@'%' WITH GRANT OPTION;"
          mysql -h 127.0.0.1 -u root -proot -e "SELECT VERSION();"

      - name: Execute tests
        run: vendor/bin/phpunit
